### Get all posts
GET http://localhost:3000/posts

### Get a specific post
GET http://localhost:3000/posts/2

### Insert Dummy Blog Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "eight Blog Post",
  "content": "This is the content of the new blog post.",
  "content_url": "https://example.com/image.jpg"
}


### Update a post
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "Updated Third Blog Post",
  "content": "This is the updated content for the third post."
}

### Delete a post
DELETE http://localhost:3000/posts/1
